# Generated by Django 3.2.2 on 2021-05-22 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20210521_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default='2021-05-22 15:37:00.455785'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(default='static/images/', upload_to='static/images/'),
        ),
    ]
