# Generated by Django 3.2.2 on 2021-05-25 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20210522_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(default='staticfiles/images/', upload_to='staticfiles/images/'),
        ),
    ]
